
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Header from "@/components/Header";
import Footer from "@/components/footer";

// Load custom fonts using localFont
const geistSans = localFont({
  src: "/fonts/GeistVF.woff",  
  variable: "--font-geist-sans", 
  weight: "100 900", 
});

export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body style={{ fontFamily: "var(--font-geist-sans)" }}>
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
